# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "wa-terraform-state-07-09"
    key     = "state/wa/group-1.state"
    profile = "wa-courses"
    region  = "eu-central-1"
  }
}
